# Generated by Django 3.1 on 2020-08-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200824_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_a',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
