# Generated by Django 3.1 on 2020-08-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200824_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='list_img',
            field=models.ManyToManyField(blank=True, to='news.image_article'),
        ),
    ]
