# Generated by Django 3.1 on 2020-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200831_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
