# Generated by Django 3.1 on 2020-08-22 19:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название праздника')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание праздника')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('date_h', models.DateField(verbose_name='Дата')),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
            },
        ),
    ]
