# Generated by Django 3.1 on 2020-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='afisha',
            name='spars',
            field=models.TextField(blank=True, null=True, verbose_name='Текст записи'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название фильма'),
        ),
    ]
