# Generated by Django 3.1 on 2020-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_auto_20200915_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afisha',
            name='spars',
        ),
        migrations.AlterField(
            model_name='afisha',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст записи'),
        ),
    ]
