# Generated by Django 3.1 on 2020-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0004_auto_20200915_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='afisha',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='afisha',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='afisha',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Время'),
        ),
    ]
