# Generated by Django 3.1 on 2020-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0005_auto_20200918_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='afisha',
            name='timefilm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Время показа'),
        ),
    ]
