# Generated by Django 3.1 on 2020-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0008_auto_20200922_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afisha',
            name='imagekin',
            field=models.URLField(blank=True, max_length=120, null=True, verbose_name='Внешняя ссылка'),
        ),
    ]
