# Generated by Django 3.1 on 2020-09-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0009_auto_20200922_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afisha',
            name='image',
        ),
    ]
