# Generated by Django 3.1 on 2020-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_site', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('descript', models.CharField(max_length=100, verbose_name='Название в шапке сайта')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона на главной')),
                ('info_pres', models.BooleanField(verbose_name='Показать блок информации')),
                ('holiday_pres', models.BooleanField(verbose_name='Показать блок <Праздники>')),
                ('video_pres', models.BooleanField(verbose_name='Показать видео блок')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
