# Generated by Django 3.1 on 2020-08-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Setting',
        ),
    ]
