# Generated by Django 3.1 on 2020-08-22 20:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200822_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование услуги')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание услуги')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('file', models.FileField(blank=True, upload_to='document/', verbose_name='Фаил')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
