# Generated by Django 3.1 on 2020-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Дата публикаци')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название видео')),
                ('description', models.CharField(max_length=250, verbose_name='Описание видео (необязательно)')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение видео')),
                ('file', models.FileField(upload_to='video/', verbose_name='Фаил')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
