# Generated by Django 3.1 on 2020-08-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание видео (необязательно)'),
        ),
    ]
